package org.vaadin.example;

import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.html.H2;
import com.vaadin.flow.component.html.ListItem;
import com.vaadin.flow.component.html.UnorderedList;
import com.vaadin.flow.router.Route;

/**
 * Trace of the 18 HtmlFlow-Datastar-Examples examples in Vaadin Flow.
 * Route "/" - each entry links to the corresponding Vaadin view (route = example name).
 */
@Route("")
public class IndexView extends VerticalLayout {

    public IndexView() {
        add(new H2("BRHC trace - 18 examples in Vaadin Flow"));
        add(new com.vaadin.flow.component.html.Paragraph(
            "Reimplementation of the HtmlFlow-Datastar-Examples examples (Kotlin + Datastar) "
            + "in Vaadin Flow (Java 21). In BRHC interactivity is declared in data-* "
            + "attributes generated by the server; here it is a Java component tree with push."));

        UnorderedList list = new UnorderedList();
        String[][] examples = {
            {"active-search", "Search with debounce"},
            {"bulk-update", "Bulk activation"},
            {"click-to-edit", "View/form toggle"},
            {"click-to-edit-signals", "Signals variant"},
            {"click-to-load", "Incremental paging"},
            {"counter", "Server-driven counter"},
            {"counter-signals", "Counter with signal"},
            {"delete-row", "Removal with confirmation"},
            {"edit-row", "Inline editing"},
            {"file-upload", "Upload with limit"},
            {"infinite-scroll", "Load on scroll"},
            {"inline-validation", "Field-by-field validation"},
            {"lazy-load", "Deferred content"},
            {"lazy-tabs", "On-demand tabs"},
            {"progress-bar", "Pushed progress"},
            {"progressive-load", "Page in parts"},
            {"signal-complex-domain", "Nested signals"},
            {"todo-mvc", "Full TodoMVC"},
            {"optimistic-actions", "Optimistic action with rollback"},
            {"multi-client-counter", "Counter synchronised across windows"},
            {"deeplink-state", "State from the URL (filter/page)"},
            {"streaming-input", "Stream with input in parallel"},
            {"large-list", "500 rows with keys + reorder"},
            {"binary-payload", "Native bytes + digest"},
        };
        for (String[] ex : examples) {
            // The ExampleView dispatcher uses @WildcardParameter; the direct URL
            // "example/{name}" is the simplest path and does not depend on configuring
            // RouteParameters for a wildcard parameter.
            String url = "example/" + ex[0];
            list.add(new ListItem(new com.vaadin.flow.component.html.Anchor(url, ex[0] + " - " + ex[1])));
        }
        add(list);
    }
}